---

- name: Everywhere
  become: yes
  hosts: all
  roles:
    - common
    - docker

- name: Kubernetes Master
  become: yes
  hosts: master
  roles:
    - etcd
    - kubernetes-master

- name: Kubernetes Slave
  become: yes
  hosts: slave
  roles:
    - kubernetes-slave
