- name: Installing etcd
  yum: name=etcd state=installed

- name: Copying /etc/etcd/etcd.conf
  template: src=templates/etc/etcd/etcd.conf.j2 dest=/etc/etcd/etcd.conf

- name: Enabling etcd
  service: name=etcd enabled=yes

- name: Starting etcd
  service: name=etcd state=started
