language: bash

cache: apt

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-pip 
  - sudo pip install -U pip
  - sudo pip install ansible
  - sudo pip install ansible-lint

script:
  - bash tests/ci
