---

###############################################################################

vms:
  master0:
    box: "simtechdev/centos7-x64"
    ip: 172.17.0.10
    cpus: 2
    memory: 1024
    role: master
  slave0:
    box: "simtechdev/centos7-x64"
    ip: 172.17.0.11
    cpus: 2
    memory: 1024
    role: slave
  slave1:
    box: "simtechdev/centos7-x64"
    ip: 172.17.0.12
    cpus: 2
    memory: 1024
    role: slave
  slave2:
    box: "simtechdev/centos7-x64"
    ip: 172.17.0.13
    cpus: 2
    memory: 1024
    role: slave

###############################################################################

provision:
  ansible:
    playbook: "provision/ansible/playbook.yml"

###############################################################################
