---

###############################################################################

vms:
  master0:
    box: "simtechdev/centos7-x64"
    ip: 10.0.4.1
    cpus: 2
    memory: 1024
    role: master
  slave0:
    box: "simtechdev/centos7-x64"
    ip: 10.0.4.2
    cpus: 2
    memory: 1024
    role: slave
  slave1:
    box: "simtechdev/centos7-x64"
    ip: 10.0.4.3
    cpus: 2
    memory: 1024
    role: slave
  slave2:
    box: "simtechdev/centos7-x64"
    ip: 10.0.4.4
    cpus: 2
    memory: 1024
    role: slave

###############################################################################

provision:
  ansible:
    playbook: "provision/ansible/playbook.yml"

###############################################################################
