---

- name: Installing Kubernetes API Server 
  yum: >
    name={{ item }}
    state=installed
  with_items:
    - kubernetes-client
    - kubernetes-master
  notify:
    - Enabling Kubernetes API Server
    - Starting Kubernetes API Server
    - Enabling Kubernetes Scheduler Server
    - Starting Kubernetes Scheduler Server
    - Enabling Kubernetes Controller Manager
    - Starting Kubernetes Controller Manager
    - Fixing Kubernetes permissions

- name: Copying /etc/kubernetes/apiserver
  template: >
    src=templates/etc/kubernetes/apiserver.j2
    dest=/etc/kubernetes/apiserver
  notify:
    - Restarting Kubernetes API Server
    - Restarting Kubernetes Scheduler Server
    - Restarting Kubernetes Controller Manager

- name: Starting Kubernetes API Server
  service: name=kube-apiserver state=started

- name: Fixing Kubernetes permissions
  file: >
    path={{ item }}
    owner=kube
    group=kube
  with_items:
    - /var/run/kubernetes/apiserver.crt
    - /var/run/kubernetes/apiserver.key

