---

- name: Installing kubernetes-master
  yum: name={{ item }} state=installed
  with_items:
    - kubernetes-client
    - kubernetes-master

- name: Copying /etc/kubernetes/apiserver
  template: src=templates/etc/kubernetes/apiserver.j2 dest=/etc/kubernetes/apiserver

- name: Starting Kubernetes API Server
  service: name=kube-apiserver state=started

- name: Applying permissions to certificates and private key for API Server
  file: path={{ item }} owner=kube group=kube
  with_items:
    - /var/run/kubernetes/apiserver.crt
    - /var/run/kubernetes/apiserver.key

- name: Enabling Kubernetes API Server
  service: name=kube-apiserver enabled=yes

- name: Restarting Kubernetes API Server (after permissions set)
  service: name=kube-apiserver state=started

- name: Enabling Kubernetes Scheduler
  service: name=kube-scheduler enabled=yes

- name: Starting Kubernetes Scheduler Server
  service: name=kube-scheduler state=started

- name: Enabling Kubernetes Controller Manager
  service: name=kube-controller-manager enabled=yes

- name: Starting Kubernetes Controller Manager
  service: name=kube-controller-manager state=started
