---

- name: Enabling etcd
  service: name=etcd enabled=yes

- name: Starting etcd
  service: name=etcd state=started

- name: Stopping etcd
  service: name=etcd state=stopped

- name: Restarting etcd
  service: name=etcd state=restarted

- name: Preseeding etcd data
  command: etcdctl mk "{{ flanneld_etcd_prefix }}/config" '{"Network":"{{ flanneld_ip_range }}"}'

