---

- name: Installing Kubernetes Node
  yum: >
    name={{ item }}
    state=installed
  with_items:
    - kubernetes-node
  notify:
    - Enabling Kubernetes Node
    - Starting Kubernetes Node
    - Enabling Kubernetes Proxy
    - Starting Kubernetes Proxy

- name: Copying /etc/kubernetes/kubelet
  template: >
    src=templates/etc/kubernetes/kubelet.j2
    dest=/etc/kubernetes/kubelet
  notify:
    - Restarting Kubernetes Node

- name: Copying /etc/kubernetes/proxy
  template: >
    src=templates/etc/kubernetes/proxy.j2
    dest=/etc/kubernetes/proxy
  notify:
    - Restarting Kubernetes Proxy
