---

- name: Installing Kubernetes Node
  yum: name={{ item }} state=installed
  with_items:
    - kubernetes-node

- name: Copying /etc/kubernetes/kubelet
  template: src=templates/etc/kubernetes/kubelet.j2 dest=/etc/kubernetes/kubelet

- name: Enabling Kubernetes Node
  service: name=kubelet enabled=yes

- name: Starting Kubernetes Node
  service: name=kubelet state=started

- name: Copying /etc/kubernetes/proxy
  template: src=templates/etc/kubernetes/proxy.j2 dest=/etc/kubernetes/proxy

- name: Enabling Kubernetes Proxy
  service: name=kube-proxy enabled=yes

- name: Starting Kubernetes Proxy
  service: name=kube-proxy state=started

