---

###############################################################################

- name: Enabling Kubernetes Node
  service: name=kubelet enabled=yes

- name: Starting Kubernetes Node
  service: name=kubelet state=started

- name: Stopping Kubernetes Node
  service: name=kubelet state=stopped

- name: Restarting Kubernetes Node
  service: name=kubelet state=restarted

###############################################################################

- name: Enabling Kubernetes Proxy
  service: name=kube-proxy enabled=yes

- name: Starting Kubernetes Proxy
  service: name=kube-proxy state=started

- name: Stopping Kubernetes Proxy
  service: name=kube-proxy state=stopped

- name: Restarting Kubernetes Proxy
  service: name=kube-proxy state=restarted

###############################################################################
