---

- name: Installing flanneld
  yum: >
    name=flannel
    state=installed
  notify:
    - Starting flanneld

- name: Copying /etc/sysconfig/flanneld
  template: >
    src=templates/etc/sysconfig/flanneld.j2
    dest=/etc/sysconfig/flanneld
  notify:
    - Enabling flanneld
    - Restarting flanneld
